### ISSUE TITLE
InteropTools & Xbox One

### ISSUE THREAD

**Issue by grilledcheesesandwich** [gus33000/InteropTools#1]
I have been experimenting with InteropTools for several years on various Mobile devices.  Some of which were the HTC 8x and the Liquid Jade Primo.  Then a couple or three years back i installed InteropTools on my Xbox one.  First through the developer console then The Microsoft Store release.  And to my surprise after installing some dependencies i was able to browse the Xbox One's registry hive.  Neat stuff.  Since I was able to transfer dependency packages through the web console on a separate PC directly to your app I have an the idea.  What if this could be used to install more UWP applications to further explore the inner system of Xbox console?

**Comment by gus33000** [comment]
Hi. This application is dead. It has been so for a few years now. I encourage you to read the readme for more details about why this repository exists and why the application is dead.

Regards, Gustave
