### ISSUE TITLE
Interop Tools Legacy says I should fall back to the unreleased Interop Tools L version instead

### ISSUE THREAD

**Issue by andreszs** [gus33000/InteropTools#7]
After opening **Version 2.1.24.0 (Legacy)** on my Lumia 925 updated to Windows 10.0.10586 (version 1511) I'm greeted with this cryptic message asking the user to fall back to _Interop Tools L_:

![image](https://github.com/user-attachments/assets/2973a047-eddc-48c6-986d-aab7039611a2)

Considering I've download the "2.1.24.0 (Legacy)" from your [Releases](https://github.com/gus33000/InteropTools/releases/tag/v2.1.24.0) page, then we can conclude that the L version is not the Legacy version, obviously. Your README says noting about an "Interop Tools L".

1. What Windows version is required to have extensions?
2. What does it mean to "fully use the app"?
3. Where can we download the last L version and why it's not mentioned in the README?

Currently, the only way to find last L version is to browse the 63 pages of [this](https://xdaforums.com/t/interop-tools-a-versatile-registry-app-for-all-devices-now-on-github.3445271/) topic in backwards order to find your attachment.

As you can see, regardless of how powerful the app is and all the time you invested on it, getting started with it can be really confusing. Maybe you could update the README here to clarify all this, thanks.

**Comment by gus33000** [comment]
- L is the Legacy version
- You can ignore below disclaimer and fully use the app with no functionality loss
- You downloaded it

L and S are shorthands for Legacy and Store, UIs were small on some phones and having such long names could have been confusing and unreadable.

The README was created *years* after the app was abandonned, its a reference source code repo for the app that used to be a thing years ago. Its not meant to serve as a "this is an active app and here's how to use it" kind of thing.

Its a source drop and binary drop of years old latest versions, comes with no warranty or support

The old XDA thread post you linked has a terribly outdated version linked to it of L, the latest one is the one attached on this github release page, you did nothing wrong.

But we arent going to fix the ui bug showing this text nor update the readme, as the readme explains that the source code was released years after abandon of the project so future people can reference it inspect it or play with it (it, being, the source code). We dont provide support nor actively work on this thing.

**Comment by gus33000** [comment]
I have nonetheless added a foot note on the release page as i understand your frustrations, but I also think you missed the whole point of the README as well, and take slight offense with you expecting it to tell you how to use or describe the app as, after rereading it for myself, I think it describes the existence of this repository rather well.

This repo holds code for any variant, its a compile flag away, theres nothing specific to L or S either way or even normal

I hope this would clear up your issue nonetheless.
